# ░█████╗░███████╗░██████╗░░█████╗░░█████╗░██████╗░██╗████████╗███████╗███╗░░░███╗░██████╗██╗░░░░░░█████╗░██████╗░███████╗
# ██╔══██╗██╔════╝██╔════╝░██╔══██╗██╔══██╗██╔══██╗██║╚══██╔══╝██╔════╝████╗░████║██╔════╝██║░░░░░██╔══██╗██╔══██╗██╔════╝
# ███████║█████╗░░██║░░██╗░██║░░██║██║░░██║██║░░██║██║░░░██║░░░█████╗░░██╔████╔██║╚█████╗░██║░░░░░██║░░██║██████╔╝█████╗░░
# ██╔══██║██╔══╝░░██║░░╚██╗██║░░██║██║░░██║██║░░██║██║░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗██║░░░░░██║░░██║██╔══██╗██╔══╝░░
# ██║░░██║██║░░░░░╚██████╔╝╚█████╔╝╚█████╔╝██████╔╝██║░░░██║░░░███████╗██║░╚═╝░██║██████╔╝███████╗╚█████╔╝██║░░██║███████╗
# ╚═╝░░╚═╝╚═╝░░░░░░╚═════╝░░╚════╝░░╚════╝░╚═════╝░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝░╚════╝░╚═╝░░╚═╝╚══════╝
# Автор плагина: anton_flame (ТГК: https://t.me/anton_flame_coder)

settings:
  # Формат вывода эффекта в описании
  effect-format: "&6%type% %level% &f(&6%duration%&f)"
  # Формат вывода эффектов в описании
  effects-format:
    - "&fЭффекты:"
    - ""
  # Формат уровней эффектов
  effect-levels:
    1: "I"
    2: "II"
    3: "III"
    4: "IV"
    5: "V"
    6: "VI"
    7: "VII"
    8: "VIII"
    9: "IX"
    10: "X"
  # Строка, которая будет выведена вместо длительности эффекта, если длительность 0
  zero-effect-duration: "0 сек"
  # Названия эффектов (обязательно капсом)
  effects:
    ABSORPTION: "Поглощение"
    BLINDNESS: "Слепота"
    CONFUSION: "Тошнота"
    DAMAGE_RESISTANCE: "Сопротивление"
    FAST_DIGGING: "Спешка"
    FIRE_RESISTANCE: "Огнестойкость"
    GLOWING: "Свечение"
    HARM: "Моментальный урон"
    HEAL: "Исцеление"
    HEALTH_BOOST: "Прилив здоровья"
    HUNGER: "Голод"
    INCREASE_DAMAGE: "Сила"
    INVISIBILITY: "Невидимость"
    JUMP: "Прыгучесть"
    LEVITATION: "Левитация"
    LUCK: "Удача"
    NIGHT_VISION: "Ночное зрение"
    POISON: "Отравление"
    REGENERATION: "Регенерация"
    SATURATION: "Насыщенность"
    SLOW: "Замедление"
    SLOW_DIGGING: "Усталость"
    SLOW_FALLING: "Плавное падение"
    SPEED: "Скорость"
    UNLUCK: "Невезение"
    WATER_BREATHING: "Подводное дыхание"
    WEAKNESS: "Слабость"
    WITHER: "Иссушение"

  # Формат вывода зачарования в описании
  enchant-format: "&6%enchant% %level%"
  # Формат вывода зачарований в описании
  enchants-format:
    - "&fЗачарования:"
    - ""
  # Формат уровней зачарований
  enchant-levels:
    1: "I"
    2: "II"
    3: "III"
    4: "IV"
    5: "V"
    6: "VI"
    7: "VII"
    8: "VIII"
    9: "IX"
    10: "X"
  # Названия зачарований
  enchants:
    PROTECTION_ENVIRONMENTAL: "Защита"
    PROTECTION_FIRE: "Огнеупорность"
    PROTECTION_FALL: "Невесомость"
    PROTECTION_EXPLOSIONS: "Взрывоустойчивость"
    PROTECTION_PROJECTILE: "Защита от снарядов"
    OXYGEN: "Подводное дыхание"
    WATER_WORKER: "Подводник"
    THORNS: "Шипы"
    DEPTH_STRIDER: "Подводная ходьба"
    FROST_WALKER: "Ледоход"
    BINDING_CURSE: "Проклятье несъёмности"
    DAMAGE_ALL: "Острота"
    DAMAGE_UNDEAD: "Небесная кара"
    DAMAGE_ARTHROPODS: "Бич членистоногих"
    KNOCKBACK: "Отдача"
    FIRE_ASPECT: "Заговор огня"
    LOOT_BONUS_MOBS: "Добыча"
    SWEEPING_EDGE: "Разящий клинок"
    DIG_SPEED: "Эффективность"
    SILK_TOUCH: "Шёлковое касание"
    DURABILITY: "Прочность"
    LOOT_BONUS_BLOCKS: "Удача"
    ARROW_DAMAGE: "Сила"
    ARROW_KNOCKBACK: "Откидывание"
    ARROW_FIRE: "Воспламенение"
    ARROW_INFINITE: "Бесконечность"
    LUCK: "Удача"
    LURE: "Приманка"
    LOYALTY: "Верность"
    IMPALING: "Пронзатель"
    RIPTIDE: "Тягун"
    CHANNELING: "Громовержец"
    MULTISHOT: "Тройной выстрел"
    QUICK_CHARGE: "Быстрая перезарядка"
    PIERCING: "Пронзающая стрела"
    MENDING: "Починка"
    VANISHING_CURSE: "Проклятье утраты"

messages:
  # Сообщение при недостатке прав
  no-permission: "&cУ Вас недостаточно прав!"
  # Сообщение при перезагрузке конфигурации
  reloaded: "&fКонфигурация была перезагружена!"
  # Хелп-сообщение для администраторов
  help:
    - ""
    - "&fПомощь по плагину &6AFGoodItemsLore&f:"
    - "&6/afgooditemslore reload &f- перезагрузить конфигурацию"
    - ""